# @Author: Haupt Joshua <HauptJ>
# @Date:   31-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: all.yml
# @Last modified by:   HauptJ
# @Last modified time: 01-Apr-2018

user: vagrant

chef_ver: 2.5.3-1
vagrant_ver: 2.0.3
terraform_ver: 0.11.7
vb_ver: 5.2

# Docker Settings
