# @Author: Haupt Joshua <HauptJ>
# @Date:   31-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: provision.yml
# @Last modified by:   Haupt Joshua
# @Last modified time: 07-Sept-2018

---
- name: Provisions VagrantBox with stuff
  hosts: all
  #strategy: debug
  become: yes


  roles:
    - boxsetup
    - git
    - editors
    - ansible
    - terraform
    - gcloud
    - swarm
    - golang
    - mongodb
    #- chef
    #- virtualbox
    #- vagrant
