# @Author: Haupt Joshua <HauptJ>
# @Date:   31-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: provision.yml
# @Last modified by:   Haupt Joshua
# @Last modified time: 26-Oct-2018

---
- name: Provisions VagrantBox with stuff
  hosts: all
  #strategy: debug
  become: yes


  roles:
    - { role: boxsetup }
    - { role: git, tags: git }
    - { role: editors, tags: editors }
    - { role: ansible, tags: ansible }
    - { role: terraform, tags: terraform }
    - { role: gcloud, tags: gcloud }
    - { role: swarm, tags: swarm }
    - { role: golang, tags: golang }
    - { role: python3, tags: python3 }
    - { role: mongodb, tags: mongodb }
    - { role: chef, tags: chef }
    - { role: virtualbox, tags: virtualbox }
    - { role: vagrant, tags: vagrant }
