# @Author: Haupt Joshua <HauptJ>
# @Date:   31-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: provision.yml
# @Last modified by:   Haupt Joshua
# @Last modified time: 10-May-2018

---
- name: Provisions VagrantBox with stuff
  hosts: all
  #strategy: debug
  become: yes


  roles:
    - boxsetup
    - editors
    - ansible
    - terraform
    - gcloud
    - docker
    - chef
    #- virtualbox
    #- vagrant
