# @Author: Haupt Joshua <HauptJ>
# @Date:   31-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: main.yml
# @Last modified by:   HauptJ
# @Last modified time: 01-Apr-2018

---
  # Tasks to install VirtualBox

- name: Install wget
  yum:
    name: wget
    state: latest

- name: Add VirtualBox Repository
  yum_repository:
    name: virtualbox
    description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

- name: Install gcc and kernel-devel for VirtualBox
  yum:
    name:
      - gcc
      - kernel-devel
    state: latest

- name: Install Virtualbox 5.2
  yum:
    name: VirtualBox-5.2
    state: latest

- name: Run VirtualBox setup script
  shell: /usr/lib/virtualbox/vboxdrv.sh setup
  ignore_errors: true
